name: Android Release Gen
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Release APK
      working-directory: ./Fase1
      run: ./gradlew assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: Fase1/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.RELEASE_STORE_FILE }}
        alias: ${{ secrets.RELEASE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.RELEASE_STORE_PASSWORD }}
        keyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}

    - uses: actions/upload-artifact@master
      with:
        name: release
        path: ${{ steps.sign_app.outputs.signedReleaseFile }}

    - uses: actions/upload-artifact@master
      with:
        name: mapping.txt
        path: app/build/outputs/mapping/release/mapping.txt