name: Artifact Download
on:
  workflow_run:
    workflows: ["Android Release Gen"]
    types:
      - completed

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Download Release Artifact
          id: download-artifact
          uses: dawidd6/action-download-artifact@v2.27.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            workflow: createRelease.yml
            workflow_conclusion: success
            event: tag
            run_id: ${{ github.event.workflow_run.id }}
            name: release
            repo: ${{ github.repository }}
            check_artifacts: false
            search_artifacts: true
            skip_unpack: false
            if_no_artifact_found: fail

        - name: Checkout
          uses: actions/checkout@v3

        - name: Get Previous Tag
          id: previous_tag
          uses: "WyriHaximus/github-action-get-previous-tag@v1"
          with:
            fallback: 1.0.1

        - name: Bumping Patch Index 
          id: bump_version_patch
          uses: christian-draeger/increment-semantic-version@1.0.2
          with:
            current-version: ${{ steps.previous_tag.outputs.tag }}
            version-fragment: 'bug'

        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: release
            tag_name: ${{ steps.bump_version_patch.outputs.next-version }}